Develop
lardc/hw-PMXUControlBoard pull request #1
Opened 2023-07-11 15:48 UTC by eugene-frost

2023-07-12 12:10 UTC, asytyi requested changes

2023-07-12 12:10 UTC, asytyi commented on Firmware/Source/Controller/DebugActions.c
> +	DataTable[REG_DBG] = !LL_GetStateSafety(); // 1 - Ok, 0 - Error
Если саму функцию `LL_GetStateSafety()` назвать `LL_IsSafetyPinOk()`, то исчезнет необходимость в комментарии здесь и везде далее, где эта функция будет использоваться. Аналогично к `LL_GetStateSelftest()`

2023-07-12 12:10 UTC, asytyi commented on Firmware/Source/Controller/LowLevel.c
> +void LL_WriteSPI1Relays(uint64_t SPI_Data_Hex)
Вот здесь не совсем понятный для меня момент и c разными функциями записи по SPI, и с упаковкой значений в uint64. Я бы предложил на этом уровне сильно логику не наращивать. Всё что связано с записью в цепочку регистров сделать в `ZcRegisterDriver`. Там уже всё есть для этого. Для записи использовать более понятное представление в виде массива uint8

2023-07-21 15:13 UTC, eugene-frost commented on Firmware/Source/Controller/LowLevel.c
> +void LL_WriteSPI1Relays(uint64_t SPI_Data_Hex)
Убрал из LL всю SPI логику в ZcRD, в LL оставил только работу с сырыми массивами uint8. 
Конвертацию между типами вынес в отдельный модуль Converter.

2023-08-09 13:28 UTC, asytyi requested changes
Общие моменты:
1. На этом этапе проект уже должен компилироваться от коммита к коммиту
2. Форматирование в документе

2023-08-09 13:28 UTC, asytyi commented on Firmware/Source/Controller/CommutationTable.h
> +		BUS2_LCTUN_4};
В таком виде инициализация массивов приведёт к ошибке компиляции:
```
Source\Controller\Controller.o:(.data.InnerCommutationTable+0x0): multiple definition of `InnerCommutationTable'
Source\Controller\Commutator.o:(.data.InnerCommutationTable+0x0): first defined here
Source\Controller\Controller.o:(.bss.CT_DFLT_Contactors+0x0): multiple definition of `CT_DFLT_Contactors'
Source\Controller\Commutator.o:(.bss.CT_DFLT_Contactors+0x0): first defined here
Source\Controller\Controller.o:(.data.CT_PE+0x0): multiple definition of `CT_PE'
Source\Controller\Commutator.o:(.data.CT_PE+0x0): first defined here
Source\Controller\Controller.o:(.data.CT_Ices_UP+0x0): multiple definition of `CT_Ices_UP'
Source\Controller\Commutator.o:(.data.CT_Ices_UP+0x0): first defined here
```
Чтобы ошибок не было массивы надо объявлять как static const. Для функций, куда массивы передаются как аргумент, объявления делать например так: `void ZcRD_WriteSPI1Relays(const uint8_t BitDataArray[]);`

А в уже в теле функции кастануть тип из конст в обычный
```
LL_WriteSPI1((uint8_t *)BitDataArray, SPI1_ARRAY_LEN_RELAYS, GPIO_SPI1_OE_REL,
			GPIO_SPI1_SS_REL);
```

2023-08-09 13:28 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +				//CONTROL_SetDeviceState(DS_InProcess, STS_InputRelayCheck_1);
🤔

2023-08-09 13:28 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +		// Relays commutation (without feedback from proximity sensors)
Комменты лучше писать на русском. Так ниже порог входа для большего числа разработчиков, которые не всегда хорошо знают английский. Исправлять написанное не надо, но для дальнейших комментариев учитывай

2023-08-09 13:28 UTC, asytyi commented on Firmware/Source/Controller/ZcRegistersDriver.c
> +	ZcRD_WriteSPI1Contactors(ContactorArray);
Здесь и далее [обрати внимание на форматирование](https://avocadotest.slack.com/archives/C015RCRJ31A/p1629811535000400?thread_ts=1628609770.000300&cid=C015RCRJ31A).

Для файлов, которые не имеют блочного форматирования (например, выравнивание табами как в Board.h, Global.h и т.п.) можно использовать применение стиля сразу ко всему файлу.

2023-08-18 09:18 UTC, eugene-frost commented on Firmware/Source/Controller/ZcRegistersDriver.c
> +	ZcRD_WriteSPI1Contactors(ContactorArray);
Да, шаблон не настроил на этом ноуте наш, каким-то дефолтным форматировал, сорре, это пробегусь поправлю по всему проекту.

2023-08-18 09:25 UTC, eugene-frost commented on Firmware/Source/Controller/CommutationTable.h
> +		BUS2_LCTUN_4};
Хм, странно, у меня компилит без ошибок и ворнингов... Что-то не донастроено у меня?

2023-10-23 09:17 UTC, closed without merging